//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ioschools.DB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        // blocker-16 (cz-dotnet-1035): Hardcoded connection string replaced with environment variable.
        // Inject DB_CONNECTION_STRING_T via Kubernetes Secret using IRSA for AWS Secrets Manager access.
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("${DB_CONNECTION_STRING_T}")]
        public string tConnectionString {
            get {
                return System.Environment.GetEnvironmentVariable("DB_CONNECTION_STRING_T") 
                    ?? ((string)(this["tConnectionString"]));
            }
        }
        
        // blocker-17 (cz-dotnet-1035): Hardcoded connection string replaced with environment variable.
        // Inject DB_CONNECTION_STRING via Kubernetes Secret using IRSA for AWS Secrets Manager access.
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("${DB_CONNECTION_STRING}")]
        public string ioschoolsConnectionString {
            get {
                return System.Environment.GetEnvironmentVariable("DB_CONNECTION_STRING") 
                    ?? ((string)(this["ioschoolsConnectionString"]));
            }
        }
    }
}
