apiVersion: v1
kind: Service
metadata:
  name: ioschools-service
  namespace: ioschools
  labels:
    app: ioschools
    managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ioschools
